[tool.poetry]
name = "competitive-programming"
version = "0.1.0"
description = ""
authors = ["Takashi Yamashina <takashi.yamashina@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
